models:
  - name: int_tripproductstep
    description: Decoding of product selection step indices (firstUndecidedStepIndex) to type & phase ID
    columns:
      - name: tripid
        data_tests:
          - not_null
          - relationships:
              arguments:
                field: tripid
                to: ref('stg_trip')
      - name: productstepindex
        data_tests:
          - not_null
      - name: productsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - departure
                  - flight
                  - hotel
                  - room
                  - ship
                  - cabin
      - name: numproductsteps
        data_tests:
          - not_null
      - name: tripphaseid
        data_tests:
          - relationships:
              arguments:
                field: tripphaseid
                to: ref('stg_tripphase')

  - name: int_travelstephierarchy
    description: Flattens the travelstep hierarchy (Hotel/DSS->City->Country, BusRouteGroup->Country, Flight, Ship individually)
    columns:
      - name: travelstepid
        data_tests:
          - not_null
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
      - name: travelstepname
        data_tests:
          - not_null
      - name: travelsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('travelsteptypes') }}"
      - name: isgdshotel
        description: Indicates if the travelstep is a GDS hotel
        data_tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: 'IN (true, false)'
              config:
                where: "travelsteptype = 'Hotel'"
          - dbt_utils.expression_is_true:
              arguments:
                expression: 'IS NULL'
              config:
                where: "travelsteptype != 'Hotel'"
      - name: cityid
        data_tests:
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
          - not_null: &where_in_city
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City')"
      - name: cityname
        data_tests:
          - not_null: *where_in_city
      - name: countryid
        data_tests:
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
          - not_null: &where_in_country
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City', 'Country', 'BusRouteGroup')"
      - name: countryname
        data_tests:
          - not_null: *where_in_country

  - name: int_triptypepriority
    description: Determines the defining trip type and other types for each trip based on priority rules
    columns:
      - name: tripid
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                field: tripid
                to: ref('stg_trip')
      - name: definingtype
        description: The defining trip type for the trip based on priority rules (can be NULL)
        data_tests:
          - accepted_values:
              arguments:
                values: "{{ var('triptypes') + ['Cruise-HotelTrip'] }}"
    data_tests:
      - dbt_utils.equal_rowcount:
          arguments:
            compare_model: ref('stg_trip')

  - name: int_tripdestinationpriority
    description: Determines the defining destination for each trip based on primarydestinationid or fallback logic
    columns:
      - name: tripid
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                field: tripid
                to: ref('stg_trip')
      - name: definingdestinationid
        description: The defining destination for the trip (can be NULL if no destinations)
        data_tests:
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
    data_tests:
      - dbt_utils.equal_rowcount:
          arguments:
            compare_model: ref('stg_trip')

  - name: int_tripphasecounts
    description: Counts the number of phases for each trip by phase type
    columns:
      - name: tripid
        data_tests:
          - not_null
          - unique
          - relationships:
              arguments:
                field: tripid
                to: ref('stg_trip')
      - name: tripnumshipphases
        description: Number of ship phases in the trip
        data_tests:
        - not_null
        - dbt_utils.accepted_range:
            arguments:
              min_value: 0
      - name: tripnumhotelphases
        description: Number of hotel phases in the trip
        data_tests:
        - not_null
        - dbt_utils.accepted_range:
            arguments:
              min_value: 0
      - name: tripnumflightphases
        description: Number of flight phases in the trip
        data_tests:
        - not_null
        - dbt_utils.not_constant
        - dbt_utils.accepted_range:
            name: tripnumphases_at_most_two
            arguments:
              # The system doesn't support trips with more than 2 flight phases, if it did we would need to revise int_tripproductstep step index calculation too
              min_value: 0
              max_value: 2
      - name: tripnumbusphases
        description: Number of bus phases in the trip
        data_tests:
        - not_null
        - dbt_utils.accepted_range:
            arguments:
              min_value: 0
      - name: tripnumduringstayservicephases
        description: Number of during stay service phases in the trip
        data_tests:
        - not_null
        - dbt_utils.accepted_range:
            arguments:
              min_value: 0
    data_tests:
      - dbt_utils.equal_rowcount:
          arguments:
            compare_model: ref('stg_trip')
      - dbt_utils.expression_is_true:
          name: trip_phase_count_consistency
          arguments:
            expression: 'tripnumshipphases + tripnumhotelphases + tripnumflightphases + tripnumbusphases + tripnumduringstayservicephases = tripnumphases'

unit_tests:
  # For int_travelstephierarchy
  - name: travelstephierarchy_test_hoteldss_citybus_country
    model: int_travelstephierarchy
    given:
      - input: ref('stg_travelstep')
        rows:
          # Countries
          - { travelstepid: 1, travelstepname: 'Viro', travelsteptype: 'Country', parentid: null }
          - { travelstepid: 2, travelstepname: 'Ruotsi', travelsteptype: 'Country', parentid: null }
          # Cities
          - { travelstepid: 3, travelstepname: 'Tallinna', travelsteptype: 'City', parentid: 1 }
          - { travelstepid: 4, travelstepname: 'Pärnu', travelsteptype: 'City', parentid: 1 }
          # A hotel
          - { travelstepid: 5, travelstepname: 'Viru', travelsteptype: 'Hotel', parentid: 3, sellhotelfromgds: true }
          # A during stay service
          - { travelstepid: 6, travelstepname: 'Karaokebaarikierros', travelsteptype: 'DuringStayService', parentid: 3 }
          # A bus route group
          - { travelstepid: 7, travelstepname: 'Tallinna-Pärnu', travelsteptype: 'BusRouteGroup', parentid: 1 }
    expect:
      rows:
        - { travelstepid: 1, travelstepname: 'Viro', travelsteptype: 'Country', isgdshotel: null, cityid: null, cityname: null, countryid: 1, countryname: 'Viro' }
        - { travelstepid: 2, travelstepname: 'Ruotsi', travelsteptype: 'Country', isgdshotel: null, cityid: null, cityname: null, countryid: 2, countryname: 'Ruotsi' }
        - { travelstepid: 3, travelstepname: 'Tallinna', travelsteptype: 'City', isgdshotel: null, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 4, travelstepname: 'Pärnu', travelsteptype: 'City', isgdshotel: null, cityid: 4, cityname: 'Pärnu', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 5, travelstepname: 'Viru', travelsteptype: 'Hotel', isgdshotel: true, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 6, travelstepname: 'Karaokebaarikierros', travelsteptype: 'DuringStayService', isgdshotel: null, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 7, travelstepname: 'Tallinna-Pärnu', travelsteptype: 'BusRouteGroup', isgdshotel: null, cityid: null, cityname: null, countryid: 1, countryname: 'Viro' }
  - name: travelstephierarchy_test_flight_ship
    model: int_travelstephierarchy
    given:
      - input: ref('stg_travelstep')
        rows:
          # A flight
          - { travelstepid: 10, travelstepname: 'Helsinki-Tallinna Finnair', travelsteptype: 'Flight', parentid: 998 }
          # A ship
          - { travelstepid: 11, travelstepname: 'Helsinki-Tallinna Ferry', travelsteptype: 'Ship', parentid: 999 }
    expect:
      rows:
        - { travelstepid: 10, travelstepname: 'Helsinki-Tallinna Finnair', travelsteptype: 'Flight', isgdshotel: null, cityid: null, cityname: null, countryid: null, countryname: null }
        - { travelstepid: 11, travelstepname: 'Helsinki-Tallinna Ferry', travelsteptype: 'Ship', isgdshotel: null, cityid: null, cityname: null, countryid: null, countryname: null }

  # For int_triptypepriority
  - name: triptypepriority_test_definingtype_from_primarytype
    model: int_triptypepriority
    given:
      - input: ref('stg_trip')
        rows:
          # This should get the defining type from primarytype
          - { tripid: 1001, name: 'Floating Spa 23h', primarytype: 'Cruise' }
      - input: ref('stg_triptype')
        rows:
          - { tripid: 1001, type: 'Cruise' }
          - { tripid: 1001, type: 'SpaTrip' }
    expect:
      rows:
        - { tripid: 1001, definingtype: 'Cruise', iscruise: true, ishoteltrip: false, isspatrip: true, istour: false }
  - name: triptypepriority_test_without_primarytype
    model: int_triptypepriority
    given:
      - input: ref('stg_trip')
        rows:
          - { tripid: 999, name: 'fake-give-type-to-redshift-adapter', primarytype: 'annoying-bug' }
          - { tripid: 1002, name: 'Luxury Hotels Around the Baltic', primarytype: null }
          - { tripid: 1003, name: 'Wild Cruise, Hangover Hotel', primarytype: null }
      - input: ref('stg_triptype')
        rows:
          - { tripid: 1002, type: 'HotelTrip' }
          - { tripid: 1002, type: 'Tour' } # Takes precedence
          - { tripid: 1003, type: 'Cruise' } # Equal...
          - { tripid: 1003, type: 'HotelTrip' } # ...weight, concatenated
    expect:
      rows:
        - { tripid: 999, definingtype: 'annoying-bug', iscruise: false, ishoteltrip: false, isspatrip: false, istour: false }
        - { tripid: 1002, definingtype: 'Tour', iscruise: false, ishoteltrip: true, isspatrip: false, istour: true }
        - { tripid: 1003, definingtype: 'Cruise-HotelTrip', iscruise: true, ishoteltrip: true, isspatrip: false, istour: false }
  - name: triptypepriority_test_no_types
    model: int_triptypepriority
    given:
      - input: ref('stg_trip')
        rows:
          - { tripid: 999, name: 'fake-give-type-to-redshift-adapter', primarytype: 'annoying-bug' }
          - { tripid: 1004, name: 'Mystery Trip', primarytype: null }
      - input: ref('stg_triptype')
        rows: []
    expect:
      rows:
        - { tripid: 999, definingtype: 'annoying-bug', iscruise: false, ishoteltrip: false, isspatrip: false, istour: false }
        - { tripid: 1004, definingtype: null, iscruise: false, ishoteltrip: false, isspatrip: false, istour: false }

  # For int_tripdestinationpriority
  - name: tripdestinationpriority_test_primarydestinationid_set
    model: int_tripdestinationpriority
    given:
      - input: ref('stg_trip')
        rows:
          - { tripid: 2001, primarydestinationid: 11 }
          - { tripid: 2002, primarydestinationid: 20 }
      - input: ref('stg_tripdestination')
        rows:
          - { tripid: 2001, travelstepid: 10 }
          - { tripid: 2001, travelstepid: 11 }
          - { tripid: 2002, travelstepid: 20 }
      - input: ref('stg_travelstep')
        rows:
          - { travelstepid: 10, travelsteptype: 'Hotel' }
          - { travelstepid: 11, travelsteptype: 'City' }
          - { travelstepid: 20, travelsteptype: 'Country' }
    expect:
      rows:
        - { tripid: 2001, definingdestinationid: 11 }
        - { tripid: 2002, definingdestinationid: 20 }
  - name: tripdestinationpriority_test_fallback_most_granular_singular
    model: int_tripdestinationpriority
    given:
      - input: ref('stg_trip')
        format: sql
        rows: |
          select 2003 as tripid, cast(null as bigint) as primarydestinationid union all
          select 2004 as tripid, cast(null as bigint) as primarydestinationid
      - input: ref('stg_tripdestination')
        rows:
          # Trip 2003: One hotel (granularity 30) and one city (20) -> picks hotel (more granular)
          - { tripid: 2003, travelstepid: 30 }
          - { tripid: 2003, travelstepid: 31 }
          # Trip 2004: Two cities (20) and one country (11) -> picks country (singular)
          - { tripid: 2004, travelstepid: 40 }
          - { tripid: 2004, travelstepid: 41 }
          - { tripid: 2004, travelstepid: 42 }
      - input: ref('stg_travelstep')
        rows:
          - { travelstepid: 30, travelsteptype: 'Hotel' }
          - { travelstepid: 31, travelsteptype: 'City' }
          - { travelstepid: 40, travelsteptype: 'City' }
          - { travelstepid: 41, travelsteptype: 'City' }
          - { travelstepid: 42, travelsteptype: 'Country' }
    expect:
      rows:
        - { tripid: 2003, definingdestinationid: 30 }
        - { tripid: 2004, definingdestinationid: 42 }
  - name: tripdestinationpriority_test_no_destinations
    model: int_tripdestinationpriority
    given:
      - input: ref('stg_trip')
        format: sql
        rows: |
          select 2007 as tripid, cast(null as bigint) as primarydestinationid
      - input: ref('stg_tripdestination')
        rows: []
      - input: ref('stg_travelstep')
        rows: []
    expect:
      rows:
        - { tripid: 2007, definingdestinationid: null }

  # For int_tripphasecounts
  - name: tripphasecounts_test_multiple_phase_types
    model: int_tripphasecounts
    given:
      - input: ref('stg_trip')
        rows:
          - { tripid: 3001 }
          - { tripid: 3002 }
      - input: ref('stg_tripphase')
        rows:
          # Trip 3001: 2 hotels, 1 ship, 1 bus
          - { tripid: 3001, tripphasetype: 'Hotel' }
          - { tripid: 3001, tripphasetype: 'Hotel' }
          - { tripid: 3001, tripphasetype: 'Ship' }
          - { tripid: 3001, tripphasetype: 'Bus' }
          # Trip 3002: 1 flight, 1 hotel
          - { tripid: 3002, tripphasetype: 'Flight' }
          - { tripid: 3002, tripphasetype: 'Hotel' }
    expect:
      rows:
        - { tripid: 3001, tripnumshipphases: 1, tripnumhotelphases: 2, tripnumbusphases: 1, tripnumflightphases: 0, tripnumduringstayservicephases: 0, tripnumphases: 4 }
        - { tripid: 3002, tripnumshipphases: 0, tripnumhotelphases: 1, tripnumbusphases: 0, tripnumflightphases: 1, tripnumduringstayservicephases: 0, tripnumphases: 2 }
  - name: tripphasecounts_test_no_phases
    model: int_tripphasecounts
    given:
      - input: ref('stg_trip')
        rows:
          - { tripid: 3003 }
      - input: ref('stg_tripphase')
        rows: []
    expect:
      rows:
        - { tripid: 3003, tripnumshipphases: 0, tripnumhotelphases: 0, tripnumbusphases: 0, tripnumflightphases: 0, tripnumduringstayservicephases: 0, tripnumphases: 0 }