models:
  - name: int_tripproductstep
    description: Decoding of product selection step indices (firstUndecidedStepIndex) to type & phase ID
    columns:
      - name: tripid
        data_tests:
          - not_null
          - relationships:
              arguments:
                field: tripid
                to: ref('stg_trip')
      - name: productstepindex
        data_tests:
          - not_null
      - name: productsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - departure
                  - flight
                  - hotel
                  - room
                  - ship
                  - cabin
      - name: numproductsteps
        data_tests:
          - not_null
      - name: tripphaseid
        data_tests:
          - relationships:
              arguments:
                field: tripphaseid
                to: ref('stg_tripphase')

  - name: int_travelstephierarchy
    description: Flattens the travelstep hierarchy (Hotel/DSS->City->Country, BusRouteGroup->Country, Flight, Ship individually)
    columns:
      - name: travelstepid
        data_tests:
          - not_null
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
      - name: travelstepname
        data_tests:
          - not_null
      - name: travelsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('travelsteptypes') }}"
      - name: isgdshotel
        description: Indicates if the travelstep is a GDS hotel
        data_tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: 'IN (true, false)'
              config:
                where: "travelsteptype = 'Hotel'"
          - dbt_utils.expression_is_true:
              arguments:
                expression: 'IS NULL'
              config:
                where: "travelsteptype != 'Hotel'"
      - name: cityid
        data_tests:
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
          - not_null: &where_in_city
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City')"
      - name: cityname
        data_tests:
          - not_null: *where_in_city
      - name: countryid
        data_tests:
          - relationships:
              arguments:
                field: travelstepid
                to: ref('stg_travelstep')
          - not_null: &where_in_country
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City', 'Country', 'BusRouteGroup')"
      - name: countryname
        data_tests:
          - not_null: *where_in_country

unit_tests:
  - name: travelstephierarchy_test_hoteldss_citybus_country
    model: int_travelstephierarchy
    given:
      - input: ref('stg_travelstep')
        rows:
          # Countries
          - { travelstepid: 1, travelstepname: 'Viro', travelsteptype: 'Country', parentid: null }
          - { travelstepid: 2, travelstepname: 'Ruotsi', travelsteptype: 'Country', parentid: null }
          # Cities
          - { travelstepid: 3, travelstepname: 'Tallinna', travelsteptype: 'City', parentid: 1 }
          - { travelstepid: 4, travelstepname: 'Pärnu', travelsteptype: 'City', parentid: 1 }
          # A hotel
          - { travelstepid: 5, travelstepname: 'Viru', travelsteptype: 'Hotel', parentid: 3, sellhotelfromgds: true }
          # A during stay service
          - { travelstepid: 6, travelstepname: 'Karaokebaarikierros', travelsteptype: 'DuringStayService', parentid: 3 }
          # A bus route group
          - { travelstepid: 7, travelstepname: 'Tallinna-Pärnu', travelsteptype: 'BusRouteGroup', parentid: 1 }
    expect:
      rows:
        - { travelstepid: 1, travelstepname: 'Viro', travelsteptype: 'Country', isgdshotel: null, cityid: null, cityname: null, countryid: 1, countryname: 'Viro' }
        - { travelstepid: 2, travelstepname: 'Ruotsi', travelsteptype: 'Country', isgdshotel: null, cityid: null, cityname: null, countryid: 2, countryname: 'Ruotsi' }
        - { travelstepid: 3, travelstepname: 'Tallinna', travelsteptype: 'City', isgdshotel: null, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 4, travelstepname: 'Pärnu', travelsteptype: 'City', isgdshotel: null, cityid: 4, cityname: 'Pärnu', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 5, travelstepname: 'Viru', travelsteptype: 'Hotel', isgdshotel: true, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 6, travelstepname: 'Karaokebaarikierros', travelsteptype: 'DuringStayService', isgdshotel: null, cityid: 3, cityname: 'Tallinna', countryid: 1, countryname: 'Viro' }
        - { travelstepid: 7, travelstepname: 'Tallinna-Pärnu', travelsteptype: 'BusRouteGroup', isgdshotel: null, cityid: null, cityname: null, countryid: 1, countryname: 'Viro' }
  - name: travelstephierarchy_test_flight_ship
    model: int_travelstephierarchy
    given:
      - input: ref('stg_travelstep')
        rows:
          # A flight
          - { travelstepid: 10, travelstepname: 'Helsinki-Tallinna Finnair', travelsteptype: 'Flight', parentid: 998 }
          # A ship
          - { travelstepid: 11, travelstepname: 'Helsinki-Tallinna Ferry', travelsteptype: 'Ship', parentid: 999 }
    expect:
      rows:
        - { travelstepid: 10, travelstepname: 'Helsinki-Tallinna Finnair', travelsteptype: 'Flight', isgdshotel: null, cityid: null, cityname: null, countryid: null, countryname: null }
        - { travelstepid: 11, travelstepname: 'Helsinki-Tallinna Ferry', travelsteptype: 'Ship', isgdshotel: null, cityid: null, cityname: null, countryid: null, countryname: null }