models:
  - name: dim_trip
    description: Dimension table for trips booked in reservations
    columns:
      - name: tripid
        description: Unique identifier for the trip
        data_tests:
        - not_null
        - unique
        - relationships:
            arguments:
              field: tripid
              to: ref('stg_trip')
      - name: tripname
        description: Name of the trip
        data_tests:
        - not_null
      - name: tripisarchived
        description: Indicates if the trip is archived
        data_tests:
        - accepted_values:
            arguments:
              values: [true, false]
      - name: definingtype
        data_tests:
          - dbt_utils.at_least_one
      - name: iscruise
        data_tests: &has_non_constant_values_truefalse
          - not_null
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values: [true, false]
      - name: ishoteltrip
        data_tests: *has_non_constant_values_truefalse
      - name: isspatrip
        data_tests: *has_non_constant_values_truefalse
      - name: istour
        data_tests: *has_non_constant_values_truefalse
      - name: tripnumphases
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.expression_is_true:
              name: tripnumphases_positive
              arguments:
                expression: '>= 0'
      - name: destinationid
        data_tests: &has_non_constant_travelstepid
          - dbt_utils.at_least_one
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
      - name: destinationtype
        data_tests:
          - dbt_utils.at_least_one
          - dbt_utils.not_constant
      - name: destinationhotelid
        data_tests: *has_non_constant_travelstepid
      - name: destinationcityid
        data_tests: *has_non_constant_travelstepid
      - name: destinationcountryid
        data_tests: *has_non_constant_travelstepid
      - name: destinationshipid
        data_tests: *has_non_constant_travelstepid
    data_tests:
      - dbt_utils.equal_rowcount:
          arguments:
            compare_model: ref('stg_trip')

  - name: fct_reservation_funnel
    description: Fact table for funnel progress of each reservation
    columns:
      - name: reservationid
        description: Unique identifier for the reservation
        data_tests:
        - not_null
        - unique
        - relationships:
            arguments:
              field: reservationid
              to: ref('stg_reservation')
      - name: tripid
        description: Unique identifier for the trip associated with the reservation
        data_tests:
        - not_null
        - relationships:
            arguments:
              field: tripid
              to: ref('dim_trip')
      # TODO other columns
    data_tests:
      - dbt_utils.expression_is_true:
          name: productselection_abandoned_must_have_abandonstep
          arguments:
            expression: finalstage != 'ProductSelection' or abandonproductsteptype is not null
      - dbt_utils.expression_is_true:
          name: productselection_completed_must_not_have_abandonstep
          arguments:
            expression: finalstage = 'ProductSelection' or abandonproductsteptype is null