models:
  - name: dim_trip
    description: Dimension table for trips booked in reservations
    columns:
      - name: tripid
        description: Unique identifier for the trip
        data_tests:
        - not_null
        - unique
        - relationships:
            arguments:
              field: tripid
              to: ref('stg_trip')
      - name: tripname
        description: Name of the trip
        data_tests:
        - not_null
      - name: tripisarchived
        description: Indicates if the trip is archived
        data_tests:
        - accepted_values:
            arguments:
              values: [true, false]
      - name: definingtype
        data_tests:
          - dbt_utils.at_least_one
      - name: iscruise
        data_tests: &has_non_constant_values_truefalse
          - not_null
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values: [true, false]
      - name: ishoteltrip
        data_tests: *has_non_constant_values_truefalse
      - name: isspatrip
        data_tests: *has_non_constant_values_truefalse
      - name: istour
        data_tests: *has_non_constant_values_truefalse
      - name: tripnumphases
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              name: tripnumphases_positive
              arguments:
                min_value: 0
      - name: destinationid
        data_tests: &has_non_constant_travelstepid
          - dbt_utils.at_least_one
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
      - name: destinationtype
        data_tests:
          - dbt_utils.at_least_one
          - dbt_utils.not_constant
      - name: destinationhotelid
        data_tests: *has_non_constant_travelstepid
      - name: destinationcityid
        data_tests: *has_non_constant_travelstepid
      - name: destinationcountryid
        data_tests: *has_non_constant_travelstepid
      - name: destinationshipid
        data_tests: *has_non_constant_travelstepid
    data_tests:
      - dbt_utils.equal_rowcount:
          arguments:
            compare_model: ref('stg_trip')

  - name: fct_reservation_funnel
    description: Fact table for funnel progress of each reservation
    columns:
      - name: reservationid
        description: Unique identifier for the reservation
        data_tests: &reservation_fk_tests
        - not_null
        - unique
        - relationships:
            arguments:
              field: reservationid
              to: ref('stg_reservation')
      - name: tripid
        description: Unique identifier for the trip associated with the reservation
        data_tests:
        - not_null
        - relationships:
            arguments:
              field: tripid
              to: ref('dim_trip')
      # TODO other columns
    data_tests:
      - dbt_utils.expression_is_true:
          name: productselection_abandoned_must_have_abandonstep
          arguments:
            expression: finalstage != 'ProductSelection' or abandonproductsteptype is not null
      - dbt_utils.expression_is_true:
          name: productselection_completed_must_not_have_abandonstep
          arguments:
            expression: finalstage = 'ProductSelection' or abandonproductsteptype is null

  - name: dim_passengergroup
    description: Dimension table for passenger groups of each reservation
    columns:
      - name: reservationid
        data_tests: *reservation_fk_tests
      - name: departureyear
        data_tests:
          - not_null
          - dbt_utils.not_constant
      - name: departureyearmonth
        data_tests:
          - not_null
          - dbt_utils.not_constant
      - name: numpassengers
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
      - name: numadults
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: "numpassengers"
      - name: numchildren
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: "numpassengers"
      - name: numexactagepassengers
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: "numpassengers"
      - name: allagesknown
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values: [true, false]
      - name: groupcategory
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values:
                  - AdultSolo
                  - AdultCouple
                  - AdultGroup
                  - FamilyWithSmallChildren
                  - FamilyWithSchoolChildren
                  - Other
      - name: adultagecategory
        data_tests:
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values: [Young, MiddleAged, Pensioner]
          - not_null:
              config:
                where: "allagesknown = true and numadults > 0"
      - name: minadultage
        data_tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: "avgadultage"
              config:
                where: "minadultage is not null"
      - name: maxadultage
        data_tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: "avgadultage"
                max_value: 120
              config:
                where: "maxadultage is not null"
      - name: minchildage
        data_tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: "avgchildage"
              config:
                where: "minchildage is not null"
      - name: maxchildage
        data_tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: "avgchildage"
                max_value: 17
              config:
                where: "maxchildage is not null"
    data_tests:
      - dbt_utils.expression_is_true:
          name: passenger_count_consistency
          arguments:
            expression: "numadults + numchildren = numpassengers"
      - dbt_utils.expression_is_true:
          name: childage_breakdown_consistency
          arguments:
            expression: "numsmallchildren + numschoolchildren = numchildren"
      - dbt_utils.expression_is_true:
          name: adultage_breakdown_consistency
          arguments:
            expression: "numyoungadults + nummiddleagedadults + numpensioners = numadults"
          config:
            where: "allagesknown = true"