version: 2
sources:
  - name: erp_raw
    database: dev
    schema: "erp_spectrum"
    tables:
      - name: ebdb_public_reservation
      - name: ebdb_public_passenger
      - name: ebdb_public_person
      - name: ebdb_public_reservedproduct
      - name: ebdb_public_product
      - name: ebdb_public_resource
      - name: ebdb_public_quota
      - name: ebdb_public_travelstep
      - name: ebdb_public_waypoint
      - name: ebdb_public_location
      - name: ebdb_public_trip
      - name: ebdb_public_tripphase
      - name: ebdb_public_tripdestination
      - name: ebdb_public_triptype

models:
  - name: stg_trip
    columns:
      - name: tripid
        tests:
          - unique
          - not_null
      - name: primarydestinationid
        tests:
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid

  - name: stg_travelstep
    columns:
      - name: travelstepid
        tests:
          - unique
          - not_null

  - name: stg_tripdestination
    columns:
      - name: tripid
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_trip')
                field: tripid
      - name: travelstepid
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - travelstepid

  - name: stg_triptype
    columns:
      - name: tripid
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_trip')
                field: tripid
      - name: type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['HotelTrip', 'SpaTrip', 'Cruise', 'Tour']
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - type