version: 2
sources:
  - name: erp_raw
    database: dev
    schema: "erp_spectrum"
    tables:
      - name: ebdb_public_reservation
      - name: ebdb_public_passenger
      - name: ebdb_public_person
      - name: ebdb_public_reservedproduct
      - name: ebdb_public_product
      - name: ebdb_public_resource
      - name: ebdb_public_quota
      - name: ebdb_public_travelstep
      - name: ebdb_public_waypoint
      - name: ebdb_public_location
      - name: ebdb_public_trip
      - name: ebdb_public_tripphase
      - name: ebdb_public_tripdestination
      - name: ebdb_public_triptype

models:
  - name: stg_trip
    columns:
      - name: tripid
        data_tests: &primary_key_tests
          - unique
          - not_null
      - name: primarydestinationid
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid

  - name: stg_travelstep
    columns:
      - name: travelstepid
        data_tests: *primary_key_tests
      - name: travelsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('travelsteptypes') }}"
      - name: parentid
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
          - not_null:
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City', 'BusRouteGroup')"

  - name: stg_tripdestination
    columns:
      - name: tripid
        data_tests: &trip_fk_tests
          - not_null
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_trip')
                field: tripid
      - name: travelstepid
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - travelstepid

  - name: stg_triptype
    columns:
      - name: tripid
        data_tests: *trip_fk_tests
      - name: type
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('triptypes') }}"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - type