version: 2
sources:
  - name: erp_raw
    database: dev
    schema: "erp_spectrum"
    tables:
      - name: ebdb_public_reservation
      - name: ebdb_public_passenger
      - name: ebdb_public_person
      - name: ebdb_public_reservedproduct
      - name: ebdb_public_product
      - name: ebdb_public_resource
      - name: ebdb_public_quota
      - name: ebdb_public_travelstep
      - name: ebdb_public_waypoint
      - name: ebdb_public_location
      - name: ebdb_public_trip
      - name: ebdb_public_tripphase
      - name: ebdb_public_tripdestination
      - name: ebdb_public_triptype

models:
  - name: stg_trip
    columns:
      - name: tripid
        data_tests: &primary_key_tests
          - unique
          - not_null
      - name: primarydestinationid
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid

  - name: stg_travelstep
    columns:
      - name: travelstepid
        data_tests: *primary_key_tests
      - name: travelsteptype
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('travelsteptypes') }}"
      - name: parentid
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
          - not_null:
              config:
                where: "travelsteptype in ('Hotel', 'DuringStayService', 'City', 'BusRouteGroup')"

  - name: stg_tripdestination
    columns:
      - name: tripid
        data_tests: &trip_fk_tests
          - not_null
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_trip')
                field: tripid
      - name: travelstepid
        data_tests: &travelstep_fk_tests
          - not_null
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - travelstepid

  - name: stg_triptype
    columns:
      - name: tripid
        data_tests: *trip_fk_tests
      - name: type
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: "{{ var('triptypes') }}"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - tripid
              - type

  - name: stg_person
    columns:
      - name: personid
        data_tests: *primary_key_tests
      - name: createyearmonth
        data_tests:
          - not_null
          - dbt_utils.not_constant
      - name: customeraccountcreateyearmonth
        data_tests:
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: "createyearmonth"
              config:
                where: "customeraccountcreateyearmonth is not null"
      - name: gender
        data_tests:
          - dbt_utils.not_constant
          - accepted_values:
              arguments:
                values: ['Male', 'Female']
      - name: hascustomeraccount
        data_tests: &varying_boolean_tests
          - not_null
          - dbt_utils.not_constant
      - name: customeraccounthasbonus
        data_tests: *varying_boolean_tests
      - name: hasclubone
        data_tests: *varying_boolean_tests

  - name: stg_reservation
    columns:
      - name: reservationid
        data_tests: *primary_key_tests
      - name: tripid
        data_tests: *trip_fk_tests
      - name: fromwebshop
        data_tests: *varying_boolean_tests
      - name: departuredate
        data_tests: &valid_date_time_tests
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 2015-01-01
      - name: customerpersonid
        data_tests: &person_fk_tests
          - dbt_utils.at_least_one
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_person')
                field: personid
      - name: createtime
        data_tests: *valid_date_time_tests
      - name: createdate
        data_tests: *valid_date_time_tests
      - name: firstundecidedreservationview
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - accepted_values:
                arguments:
                values:
                  - ProductSelection
                  - PassengerInfo
                  - ReserverInfo
                  - AdditionalServices
                  - Confirmation
      - name: firstundecidedstepindex
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0

  - name: stg_passenger
    columns:
      - name: passengerid
        data_tests: *primary_key_tests
      - name: personid
        data_tests: *person_fk_tests
      - name: reservationid
        data_tests:
          - not_null
          - dbt_utils.not_constant
          # No relationships test - apparently there is no FK constraint in source and there are orphaned Passengers for deleted? Reservations
      - name: createyearmonth
        data_tests:
          - not_null
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 2015-01-01
      - name: origincityid
        data_tests: &travelstep_optional_fk_tests
          - dbt_utils.not_constant
          - relationships:
              arguments:
                to: ref('stg_travelstep')
                field: travelstepid
      - name: returncityid
        data_tests: *travelstep_optional_fk_tests
      - name: hasowncar
        data_tests: *varying_boolean_tests
      - name: childageyears
        data_tests:
          - dbt_utils.not_constant
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 17
              config:
                where: "childageyears is not null"